apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: rsvp-app
data:
  # URL negrok
  BASE_URL: "https://semisentimentally-geyseral-cliff.ngrok-free.dev"

  # Mail Settings (Defaults from config.py)
  MAIL_SERVER: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USE_TLS: "True"
  MAIL_USE_SSL: "False"
  MAIL_DEFAULT_SENDER: "noreply.eventnotify@gmail.com"
