apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: rsvp-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: yuvalzikri/rsvp-backend:v.44
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-cluster-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-cluster-app
                  key: password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-cluster-app
                  key: host
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):5432/event_db"
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          volumeMounts:
            - name: backgrounds-volume
              mountPath: /app/backgrounds
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: backgrounds-volume
          hostPath:
            path: /project/frontend/src/background
            type: Directory
