apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngrok
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/Yuval-Zikri/RSVP.git
    targetRevision: deploy
    path: k8s/ngrok
  destination:
    server: https://kubernetes.default.svc
    namespace: rsvp-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
