apiVersion: v1
kind: Service
metadata:
  name: ngrok
  namespace: event-manager
spec:
  selector:
    app: ngrok
  ports:
    - name: http
      port: 4040
      targetPort: 4040
  type: LoadBalancer
